### PR TITLE
chore: publish the integration tests binary for snapd

### PR DESCRIPTION
**Pull request by sminez**
@olivercalder I think this should do the trick? If it works as intended then the APIs described here should work for locating and downloading the artifact: https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28

### CODE REVIEW

**Review by olivercalder — DISMISSED** [review]
Thank you, this looks great!

I downloaded the artifact manually and it seems to work. I have to figure out where to get the most recent build from within a spread test.

Also, is it possible to publish the testing snap as well as the integration tests (or bundled together)? Otherwise, we still need to snapcraft the testing snap within the spread test. See comments here: https://github.com/canonical/snapd/pull/14387/files#diff-ac4e3fdf324e9271af5b128e312c8657f070a1c4269c890f914be72a58ea4fc6

**Comment by sminez** [comment]
Ah sorry, yeah I'll get the testing snap published here as well. Now that there's been a green build I'll see if I can work out how to reliably pull the latest artifacts.

**Comment by sminez** [comment]
@olivercalder This should do the trick for downloading the latest versions of things so long as you have a GitHub API token with read access to this repo exported as `GITHUB_TOKEN` in your environment:
```bash
#!/usr/bin/env bash
BASE="https://api.github.com/repos/canonical/prompting-client"
WORKFLOW="publish-integration-tests.yaml"

function get() {
  url="$1"
  curl -s \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $GITHUB_TOKEN" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
      "$url"
}

function download() {
  url="$1"
  fname="$2"

  curl -L \
    --output "$fname" \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $GITHUB_TOKEN" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
      "$url"
}

echo "Fetching workflow id..."
WORKFLOW_ID=$(
  get "$BASE/actions/workflows/$WORKFLOW" |
    jq -r '.id'
)

echo "Fetching id of the latest run..."
RUN_ID=$(
  get "$BASE/actions/workflows/$WORKFLOW_ID/runs" |
    jq -r '.workflow_runs[0].id'
)

echo "Fetching artifact listing..."
ARTIFACTS=$(get "$BASE/actions/runs/$RUN_ID/artifacts")

echo "Dowloading integration tests binary..."
download "$(echo "$ARTIFACTS" | jq -r '.artifacts[0].archive_download_url')" \
  integration-tests.zip

echo "Dowloading testing snap..."
download "$(echo "$ARTIFACTS" | jq -r '.artifacts[1].archive_download_url')" \
  aa-prompting-test.zip
```

**Comment by matthew-hagemann** [comment]
> @olivercalder This should do the trick for downloading the latest versions of things so long as you have a GitHub API token with read access to this repo exported as `GITHUB_TOKEN` in your environment:
> 
> ```shell
> #!/usr/bin/env bash
> BASE="https://api.github.com/repos/canonical/prompting-client"
> WORKFLOW="publish-integration-tests.yaml"
> 
> function get() {
>   url="$1"
>   curl -s \
>     -H "Accept: application/vnd.github+json" \
>     -H "Authorization: Bearer $GITHUB_TOKEN" \
>     -H "X-GitHub-Api-Version: 2022-11-28" \
>       "$url"
> }
> 
> function download() {
>   url="$1"
>   fname="$2"
> 
>   curl -L \
>     --output "$fname" \
>     -H "Accept: application/vnd.github+json" \
>     -H "Authorization: Bearer $GITHUB_TOKEN" \
>     -H "X-GitHub-Api-Version: 2022-11-28" \
>       "$url"
> }
> 
> echo "Fetching workflow id..."
> WORKFLOW_ID=$(
>   get "$BASE/actions/workflows/$WORKFLOW" |
>     jq -r '.id'
> )
> 
> echo "Fetching id of the latest run..."
> RUN_ID=$(
>   get "$BASE/actions/workflows/$WORKFLOW_ID/runs" |
>     jq -r '.workflow_runs[0].id'
> )
> 
> echo "Fetching artifact listing..."
> ARTIFACTS=$(get "$BASE/actions/runs/$RUN_ID/artifacts")
> 
> echo "Dowloading integration tests binary..."
> download "$(echo "$ARTIFACTS" | jq -r '.artifacts[0].archive_download_url')" \
>   integration-tests.zip
> 
> echo "Dowloading testing snap..."
> download "$(echo "$ARTIFACTS" | jq -r '.artifacts[1].archive_download_url')" \
>   aa-prompting-test.zip
> ```

Oooh nice!

**Review by matthew-hagemann — APPROVED** [review]
For completeness pulled the `aa-prompting-test` artifact aswell. LGTM!

**Comment by olivercalder** [comment]
Thanks, this looks great! Since this repo is public, is there there any way to access the artifacts without needing a GitHub token? Or, alternatively, can we generate a read-only token which can be included in plaintext in the snapd test code? I don't think we can rely on a token stored in GitHub secrets, since we need to be able to do local spread testing outside of and unrelated to GitHub.

**Pull request merged**
