### PR TITLE
feat: add desktop icon for prompting-client-ui app

### PR DESCRIPTION
**Pull request by d-loose**
I'd appreciate it if someone could double-check that the icon now displays correctly - there's a snap build [here](https://github.com/canonical/prompting-client/actions/runs/10814453039).

UDENG-4335

### CODE REVIEW

**Review by sergio-costas — COMMENTED** [review]
Why png and svg icons? Shouldn't it work just with svg only?

**Comment by d-loose** [comment]
> Why png and svg icons? Shouldn't it work just with svg only?

I followed what @sminez did for the security center - was there a reason you added a png there? I'd be happy to just use the svg.

**Comment by sergio-costas** [comment]
No, there wasn't... It should work fine with a svg only...

**Review by sminez — APPROVED** [review]
I can confirm that the icon is working correctly with the snap build you've linked above @d-loose 

working-icon

**Comment by d-loose** [comment]
Merging this as-is, to be consistent with the other desktop apps, that also use png icons at the moment. We can test the svg in case we observe any scaling issues with the png.

**Pull request merged**
